#!/bin/bash
# Script to add a user to Linux system
if [ $(id -u) -eq 0 ]; then
echo "Welcome to Bash script for user accounts."
echo "Enter Your Choice from following options"
echo "Press 1: Add User with Password."
echo "Press 2: Add a group without password."
echo "Press 3: Add user to group."
read Choice
# checkin for user choice
case $Choice in
1)
read -p "Enter username : " username
   read -s -p "Enter password ,typing is invisible: " password
   echo
   echo "Wait it will take a few seconds as encryption in backgroud."
   egrep "^$username" /etc/passwd >/dev/null
   # checking if user exists or not
   if [ $? -eq 0 ]; then
       echo "$username exists!"
       exit 1
   else
       # if not then creating user
       pass=$(perl -e 'print crypt($ARGV[0], "password")' $password)
       useradd -m -p $pass $username
       [ $? -eq 0 ] && echo "User has been added to system!" || echo "Failed to add a user!"
   fi
;;
2)
# New group added
read -p "Enter the name of group. " groupname
sudo groupadd $groupname
   if [ $? -eq 0 ]; then
   echo "Group $groupname sucessfully added."
   else
   echo "Error not able to add group."
   fi
;;
3)
# reading group name and user name it will automatically adds new group and if group already exists it will display message of user already exist
read -p "Enter the groupname: " newgroup
sudo groupadd $newgroup
read -p "Now, enter the username: " adduser
# checking if user already exist or not
egrep "^$adduser" /etc/passwd >/dev/null
   if [ $? -eq 0 ]; then
       # if user exist adding user to group
       usermod -G $newgroup $adduser
       if [ $? -eq 0 ]; then
   echo "User $adduser sucessfully addeded to $newgroup."
   else
   echo "Error not able to add User."
   fi
   else
       # if user is does not exist
       echo "$adduser User not exists."
   fi
;;
*)
# if user enetered invalid choice other than 1,2 or 3
echo "You have not entered a valid choice"
;;
esac
else
   # if user is not run under sudo permissions
   echo "Only root may add a user to the system"
   exit 2
fi
#end
